baseURL = "http://example.org/"
languageCode = "de-de"
title = "Hugo Test Site"
theme = "ananke"
DefaultContentLanguage = "de"

[mediaTypes]
  [mediaTypes."text/enriched"]
    suffixes = ["enr"]
  [mediaTypes."text/html"]
    suffixes = ["asp"]
  [mediaTypes."application/json"]
    suffixes = ["json"]

[outputs]
  home = ["HTML", "AMP", "RSS"]
  page = ["HTML", "JSON"]
  list = ["HTML", "JSON"]
  section = ["HTML", "JSON"]
  taxonomy = ["HTML", "JSON"]
  taxonomyTerm = ["HTML", "JSON"]

[languages]
  [languages.de]
    languageName = "German"
    weight = 1
  [languages.en]
    languageName = "English"
    weight = 2
  [languages.fr]
    languageName = "Français"
    weight = 3
